# Generated by Django 5.0.6 on 2024-07-02 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='tranking',
            new_name='tracking',
        ),
    ]
