# Generated by Django 5.0.6 on 2024-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_askqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='askqa',
            name='detail_answer',
            field=models.TextField(blank=True, null=True, verbose_name='คำตอบ'),
        ),
    ]
