# Generated by Django 5.0.6 on 2024-08-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detial',
            new_name='detail',
        ),
    ]
