# Generated by Django 5.0.6 on 2024-08-16 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_profile_tel_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='normal_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.IntegerField(blank=True, default=40, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('count', models.IntegerField(default=1)),
                ('buyer_price', models.FloatField(default=0)),
                ('shipping_cost', models.FloatField(default=0)),
                ('slip', models.ImageField(upload_to='product-slip/')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.product')),
            ],
        ),
    ]
