# Generated by Django 5.0.6 on 2024-08-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_remove_product_price_product_normal_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
