# Generated by Django 5.0.6 on 2024-08-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
